# Generated by Django 3.2.5 on 2021-07-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='userId',
            field=models.PositiveIntegerField(verbose_name='post user id'),
        ),
    ]
