# Generated by Django 3.2.5 on 2021-07-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='post id'),
        ),
        migrations.AlterField(
            model_name='post',
            name='userId',
            field=models.IntegerField(verbose_name='post user id'),
        ),
    ]
