# Generated by Django 3.2.5 on 2021-07-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210729_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='post id'),
        ),
        migrations.AlterField(
            model_name='post',
            name='userId',
            field=models.PositiveIntegerField(verbose_name='post user id'),
        ),
    ]
